




CREATE TABLE PhoneType (

 primaryKey UUID NOT NULL,

 TypeName VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE Phone (

 primaryKey UUID NOT NULL,

 Number VARCHAR(255) NULL,

 PhoneType_m0 UUID NOT NULL,

 Contact_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE ContactType (

 primaryKey UUID NOT NULL,

 TypeName VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE Contact (

 primaryKey UUID NOT NULL,

 FirName VARCHAR(255) NULL,

 SurName VARCHAR(255) NULL,

 SecName VARCHAR(255) NULL,

 ContactType_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMNETLOCKDATA (

 LockKey VARCHAR(300) NOT NULL,

 UserName VARCHAR(300) NOT NULL,

 LockDate TIMESTAMP(3) NULL,

 PRIMARY KEY (LockKey));



CREATE TABLE STORMSETTINGS (

 primaryKey UUID NOT NULL,

 Module VARCHAR(1000) NULL,

 Name VARCHAR(255) NULL,

 Value TEXT NULL,

 "User" VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMAdvLimit (

 primaryKey UUID NOT NULL,

 "User" VARCHAR(255) NULL,

 Published BOOLEAN NULL,

 Module VARCHAR(255) NULL,

 Name VARCHAR(255) NULL,

 Value TEXT NULL,

 HotKeyData INT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMFILTERSETTING (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NOT NULL,

 DataObjectView VARCHAR(255) NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMWEBSEARCH (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NOT NULL,

 "Order" INT NOT NULL,

 PresentView VARCHAR(255) NOT NULL,

 DetailedView VARCHAR(255) NOT NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMFILTERDETAIL (

 primaryKey UUID NOT NULL,

 Caption VARCHAR(255) NOT NULL,

 DataObjectView VARCHAR(255) NOT NULL,

 ConnectMasterProp VARCHAR(255) NOT NULL,

 OwnerConnectProp VARCHAR(255) NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMFILTERLOOKUP (

 primaryKey UUID NOT NULL,

 DataObjectType VARCHAR(255) NOT NULL,

 Container VARCHAR(255) NULL,

 ContainerTag VARCHAR(255) NULL,

 FieldsToView VARCHAR(255) NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE UserSetting (

 primaryKey UUID NOT NULL,

 AppName VARCHAR(256) NULL,

 UserName VARCHAR(512) NULL,

 UserGuid UUID NULL,

 ModuleName VARCHAR(1024) NULL,

 ModuleGuid UUID NULL,

 SettName VARCHAR(256) NULL,

 SettGuid UUID NULL,

 SettLastAccessTime TIMESTAMP(3) NULL,

 StrVal VARCHAR(256) NULL,

 TxtVal TEXT NULL,

 IntVal INT NULL,

 BoolVal BOOLEAN NULL,

 GuidVal UUID NULL,

 DecimalVal DECIMAL(20,10) NULL,

 DateTimeVal TIMESTAMP(3) NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE ApplicationLog (

 primaryKey UUID NOT NULL,

 Category VARCHAR(64) NULL,

 EventId INT NULL,

 Priority INT NULL,

 Severity VARCHAR(32) NULL,

 Title VARCHAR(256) NULL,

 Timestamp TIMESTAMP(3) NULL,

 MachineName VARCHAR(32) NULL,

 AppDomainName VARCHAR(512) NULL,

 ProcessId VARCHAR(256) NULL,

 ProcessName VARCHAR(512) NULL,

 ThreadName VARCHAR(512) NULL,

 Win32ThreadId VARCHAR(128) NULL,

 Message VARCHAR(2500) NULL,

 FormattedMessage TEXT NULL,

 PRIMARY KEY (primaryKey));




 ALTER TABLE Phone ADD CONSTRAINT FK4744eb4843d545d2a9777e8828d648c5 FOREIGN KEY (PhoneType_m0) REFERENCES PhoneType; 
CREATE INDEX Indexacc0429bfead6fed3020feb6ee465cbe9831f901 on Phone (PhoneType_m0); 

 ALTER TABLE Phone ADD CONSTRAINT FK4eea45db5b794028907f999f6a22a337 FOREIGN KEY (Contact_m0) REFERENCES Contact; 
CREATE INDEX Index8ec920b6148fb1b2df03a0a516419de483263b10 on Phone (Contact_m0); 

 ALTER TABLE Contact ADD CONSTRAINT FK9f0010b830ce49e7a6aa8bed2c919e18 FOREIGN KEY (ContactType_m0) REFERENCES ContactType; 
CREATE INDEX Indexcfcf4717a4641a4a98a8656a0d1a917ea80f1c48 on Contact (ContactType_m0); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FK989bd310d6a545e08483bc8cd03a49ea FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FKd2980943005747838c131192f97111c0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FK7431ec49edfb44f79820f1ce32765df0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

